### ISSUE TITLE
Issue in space partitioning

### ISSUE THREAD

**Issue by kanchanchy** [DataSystemsLab/GeoTorchAI#25]
Space partitioning functions raise an error in shapely version >= 2.0

**Comment by jiayuasu** [comment]
@kanchanchy Please do not upgrade shapely to >=2.0. GeoPandas might also accidentally install shapely >=2.0. Please pin GeoPanas to 0.11.1, the last version before migrating to Shapely 2.0. Otherwise, Sedona Python will run into lots of issues on Shapely 2.0.

We will move to Shapely 2.0 when Shapely 2.0 eco system is ready.

**Comment by kanchanchy** [comment]
@jiayuasu I am not upgrading to shapely 2.0. I needed to use boundarEnvelop method of spatial RDD's in a function. I resolved this issue using ST_Envelope_Aggr() as discussed with you earlier.

**Comment by kanchanchy** [comment]
Solved by the merged pull request #24
